### ISSUE TITLE
Update Export Tool Documentation- File Formats

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/osm-export-tool#483]
Documentation need to be updated here: https://github.com/hotosm/osm-export-tool/blob/master/ui/app/components/help/ExportFormats.js

Updated list of formats is available on staging: https://export-staging.hotosm.org/en/v3/exports/new/formats

![image](https://user-images.githubusercontent.com/98902727/205624924-7270bcc9-35f3-41bf-8a26-e5fbe6e75183.png)

The list in the documentation should be updated respectively.

**Comment by mohammadareeb95** [comment]
Hey @petya-kangalova! :)
Can I work on submitting a PR towards this issue?

**Comment by petya-kangalova** [comment]
Hi @mohammadareeb95 - lovely to e-meet you!! Yes, that would be wonderful if you can start on updating the documentation- feel free to submit a PR and we will then review!

If you have any questions, I will be really happy to chat! cc: @kshitijrajsharma

**Comment by kshitijrajsharma** [comment]
To take reference stage setup is dead for now we are working on it ! I will post comment when it is up ! cc: @eternaltyro  @mohammadareeb95

**Comment by petya-kangalova** [comment]
Thanks @kshitijrajsharma !

@mohammadareeb95 in the meantime, let me know what your interests in contributing are, happy to find other areas/issues to work on in the meantime.

**Comment by mohammadareeb95** [comment]
@petya-kangalova Thanks for asking!
As a new face to the project, I'm focused on documentation but I'm willing to explore other areas as I get acquainted. Please suggest any good first issues, thanks!

**Comment by eternaltyro** [comment]
@mohammadareeb95 Documentation contributions are valuable. So thank you for your interest. Let me know if you need any assistance from us to help you with your first contribution here.

**Comment by petya-kangalova** [comment]
@eternaltyro  any update on when staging my be working?
It will be great for @mohammadareeb95  to work on updating the documentation: https://github.com/hotosm/osm-export-tool/tree/master/ui/app/components/help

@mohammadareeb95  in the meantime, it can also be helpful to read through the README.md and https://github.com/hotosm/osm-export-tool/blob/master/CONTRIBUTING.md to see if they make sense or any suggested changes?

@kshitijrajsharma  this might also be a useful documentation for @mohammadareeb95  to look at ? https://github.com/hotosm/osm-export-tool/blob/master/doc/setup-development.md

**Comment by petya-kangalova** [comment]
@mohammadareeb95   I just got an update from the team that from tomorrow if you'd like to start working on the documentation! @kshitijrajsharma is setting up the necessary configuration and env files , it will be ready from tomorrow !

Export tool stage server is Deployed with new machine database and everything  : https://export-staging.hotosm.org/en/v3/exports/new/describe
Raw Data stage is also deployed : https://raw-data-api0.hotosm.org/v1/docs

**Comment by kshitijrajsharma** [comment]
All new formats Geojson shapefile csv gpkg kml and flatgeobuf is ready on stage server ! Turkey and syria are loaded

**Comment by mohammadareeb95** [comment]
Thank you @petya-kangalova @eternaltyro @kshitijrajsharma for helping me follow up with the issues, really appreciate it. 


> All new formats Geojson sql shapefile csv gpkg kml and flatgeobuf is ready on stage server ! Turkey and syria are loaded
@kshitijrajsharma I believe that means I can submit a PR for this issue now?

**Comment by kshitijrajsharma** [comment]
Yes @mohammadareeb95  Now you can

**Comment by kshitijrajsharma** [comment]
Will check @mohammadareeb95 !

**Comment by kshitijrajsharma** [comment]
Can You try now ? @mohammadareeb95  , Try using incognito

**Comment by mohammadareeb95** [comment]
@kshitijrajsharma Now I can receive the validation email but clicking the link leads to 
![image](https://user-images.githubusercontent.com/77102111/223807960-2f03b85e-7db5-48e3-903d-5d6ae43031f6.png)

**Comment by kshitijrajsharma** [comment]
Oh ! its a known issue , Ignore it and relaunch the URL it should log you, Those formats should be working and (geojson,fgb,csv,sql ) needs documentation 
![image](https://user-images.githubusercontent.com/36752999/223808418-6e250263-700b-45d4-89e3-6d6c65776430.png)

**Comment by mohammadareeb95** [comment]
I've added a PR for this issue:https://github.com/hotosm/osm-export-tool/pull/505

**Comment by mohammadareeb95** [comment]
thanks @kshitijrajsharma for helping me out!

**Comment by casper06** [comment]
Opened #542, following up on #505 (thanks @mohammadareeb95 for the initial 
work on geojson/fgb/csv/sql back in 2023!). This adds the remaining formats 
that are selectable in the UI but still missing docs (OsmAnd .obf, PMTiles, 
MVT), and syncs the sidebar TOC with the current sections.

Happy to adjust based on feedback.
